### PR TITLE
FRENCH translation for Holiday Flare extension

### PR DESCRIPTION
**Pull request by Galixte**
FRENCH translation for holidayflare_acp.php file
FRENCH translation for info_acp_holidayflare.php file

### CODE REVIEW

**Comment by Galixte** [comment]
Hi @bonelifer,

it's OK for me, could you take a look ?

**Comment by Galixte** [comment]
Hi @tumba25,

could you take a look ?

**Comment by Galixte** [comment]
Hi @bonelifer & @tumba25,,

could you take a look ?

**Comment by Galixte** [comment]
Hi @bonelifer,

could you merge this, please ?

**Comment by bonelifer** [comment]
@Galixte  If you could please pull in the latest change into your PR. I can then merge.

**Comment by Galixte** [comment]
Fixed here: https://github.com/phpbbmodders/holiday_flare/pull/4.

**Pull request closed without merging**
